/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista;

import com.dao.DaoUsuario;
import com.modelo.Usuario;
import static com.vista.FrmPrincipalx.ii;
import java.awt.Color;
import com.utilidades.UITools;
import com.utilidades.Validacion;
import static java.awt.Frame.NORMAL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author jsidg
 */
public class FrmLogin extends javax.swing.JFrame
{

    UITools ui = new UITools();
    Validacion val = new Validacion();
    Usuario u = new Usuario();
    DaoUsuario dao = new DaoUsuario();
    
    public FrmLogin()
    {
        initComponents();
        initUi();
        borders();
    }

    private int xx;
    private int xy;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTxtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jBtnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));
        setUndecorated(true);

        jPanelTitulo.setBackground(new java.awt.Color(204, 204, 204));
        jPanelTitulo.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanelTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                jPanelTituloMouseDragged(evt);
            }
        });
        jPanelTitulo.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPanelTituloMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Control SSE");

        lblX.setBackground(new java.awt.Color(204, 204, 204));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vista/x.png"))); // NOI18N
        lblX.setOpaque(true);
        lblX.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblXMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                .addGap(0, 167, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(131, 131, 131)
                .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTxtNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTxtNombreKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Nunito", 0, 11)); // NOI18N
        jLabel2.setText("Nombre de Usuario:");

        jLabel3.setFont(new java.awt.Font("Nunito", 0, 11)); // NOI18N
        jLabel3.setText("Contraseña:");

        jBtnLogin.setBackground(new java.awt.Color(23, 165, 137));
        jBtnLogin.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jBtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLogin.setText("Ingresar");
        jBtnLogin.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jBtnLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jBtnLoginMouseReleased(evt);
            }
        });
        jBtnLogin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnLogin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnLogin)
                .addGap(34, 34, 34))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnLogin, jTxtNombre, jTxtPass});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelTituloMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanelTituloMousePressed
    {//GEN-HEADEREND:event_jPanelTituloMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanelTituloMousePressed

    private void jPanelTituloMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanelTituloMouseDragged
    {//GEN-HEADEREND:event_jPanelTituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanelTituloMouseDragged

    private void jBtnLoginMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jBtnLoginMousePressed
    {//GEN-HEADEREND:event_jBtnLoginMousePressed
        jBtnLogin.setBackground(new Color(17, 120, 100));
    }//GEN-LAST:event_jBtnLoginMousePressed

    private void jBtnLoginMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jBtnLoginMouseReleased
    {//GEN-HEADEREND:event_jBtnLoginMouseReleased
        jBtnLogin.setBackground(new Color(23, 165, 137));
    }//GEN-LAST:event_jBtnLoginMouseReleased

    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnLoginActionPerformed
    {//GEN-HEADEREND:event_jBtnLoginActionPerformed
        try
        {
            u.setNomUsuario(this.jTxtNombre.getText());
            u.setPass(String.valueOf(this.jTxtPass.getPassword()).trim());
            System.out.println(String.valueOf(this.jTxtPass.getPassword()).trim());
            if(dao.login(u))
            {
                FrmPrincipal frm = new FrmPrincipal();
                frm.setLocationRelativeTo(null);
                frm.setExtendedState(MAXIMIZED_BOTH);
                frm.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Datos Incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_jBtnLoginActionPerformed

    private void initUi()
    {
        ui.flatLabel(lblX, "#CCCCCC", "#E81123", "#DC5C66");
        ui.lblIcon(lblX, "../vista/x.png", "../vista/xW.png");
        ui.flatButton(jBtnLogin, "#D74738", "#E74C3C", "#DC5C66");
    }
    
    private void lblXMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblXMouseClicked
    {//GEN-HEADEREND:event_lblXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblXMouseClicked

    private void jTxtNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTxtNombreKeyPressed
    {//GEN-HEADEREND:event_jTxtNombreKeyPressed
        
    }//GEN-LAST:event_jTxtNombreKeyPressed

    private void borders()
    {
        jPanel1.setBorder(new MatteBorder(0, 1, 1, 1, Color.decode("#E74C3C")));
        jPanelTitulo.setBorder(new MatteBorder(1, 1, 0, 1, Color.decode("#E74C3C")));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                FrmLogin frm = new FrmLogin();
                frm.setLocationRelativeTo(null);
                frm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JPasswordField jTxtPass;
    private javax.swing.JLabel lblX;
    // End of variables declaration//GEN-END:variables
}
