/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista;

import com.dao.DaoCoordinador;
import com.dao.DaoEstudiante;
import com.dao.DaoHojaSS;
import com.dao.DaoInstitucion;
import com.dao.DaoSolicitud;
import com.modelo.Estudiante;
import com.modelo.HojaServicioSocial;
import com.modelo.Institucion;
import com.modelo.Solicitud;
import com.utilidades.Console;
import com.utilidades.UITools;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jsidg
 */
public class InternalFrmHoja extends javax.swing.JInternalFrame
{

    UITools ui = new UITools();
    Estudiante e = new Estudiante();
    Solicitud s = new Solicitud();
    Institucion i = new Institucion();
    DaoEstudiante daoE = new DaoEstudiante();
    DaoSolicitud daoS = new DaoSolicitud();
    DaoInstitucion daoI = new DaoInstitucion();
    DaoCoordinador daoC = new DaoCoordinador();
    DaoHojaSS daoH = new DaoHojaSS();

    public InternalFrmHoja()
    {
        initComponents();
        initUi();
        jTableHojas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelEstudiante = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTxtCarnet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jTxtApellidos = new javax.swing.JTextField();
        Apellidos = new javax.swing.JLabel();
        jTxtGrupo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtIdEst = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnAddEstudiante = new javax.swing.JButton();
        jBtnChangeEstudiante = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 17), new java.awt.Dimension(0, 17), new java.awt.Dimension(32767, 17));
        jPanelExtra = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTxtInicio = new javax.swing.JFormattedTextField();
        jTxtFin = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTxtEncargado = new javax.swing.JTextField();
        jBtnLimpiar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnRegistrar = new javax.swing.JButton();
        jSHoras = new javax.swing.JSpinner();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaSolicitudes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanelInstitucion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtNombreInst = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtCorreoInst = new javax.swing.JTextField();
        jTxtTelefonoInst = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtTipoInst = new javax.swing.JTextField();
        jTxtIdSolicitud = new javax.swing.JTextField();
        jTxtIdInst = new javax.swing.JTextField();
        jPanelHojas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableHojas = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setTitle("Registro de Hoja de Servicio Social");

        jPanel1.setBackground(new java.awt.Color(36, 37, 38));

        jLabel1.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hoja de Servicio Social");
        jLabel1.setPreferredSize(new java.awt.Dimension(99, 24));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        jPanelEstudiante.setBackground(new java.awt.Color(250, 250, 250));

        jLabel3.setText("Carnet:");

        jTxtCarnet.setEnabled(false);

        jLabel4.setText("Nombre:");

        jTxtNombre.setEnabled(false);

        jTxtApellidos.setEnabled(false);

        Apellidos.setText("Apellidos");

        jTxtGrupo.setEnabled(false);

        jLabel6.setText("Grupo:");

        javax.swing.GroupLayout jPanelEstudianteLayout = new javax.swing.GroupLayout(jPanelEstudiante);
        jPanelEstudiante.setLayout(jPanelEstudianteLayout);
        jPanelEstudianteLayout.setHorizontalGroup(
            jPanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTxtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Apellidos)
                    .addComponent(jTxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelEstudianteLayout.createSequentialGroup()
                        .addComponent(jTxtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtIdEst, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanelEstudianteLayout.setVerticalGroup(
            jPanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEstudianteLayout.createSequentialGroup()
                        .addComponent(Apellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTxtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Product Sans", 0, 16)); // NOI18N
        jLabel2.setText("Estudiante");

        jBtnAddEstudiante.setBackground(new java.awt.Color(46, 204, 113));
        jBtnAddEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAddEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/icons8_Sum_16px.png"))); // NOI18N
        jBtnAddEstudiante.setToolTipText("Agregar Estudiante");
        jBtnAddEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAddEstudiante.setIconTextGap(0);
        jBtnAddEstudiante.setPreferredSize(new java.awt.Dimension(73, 20));
        jBtnAddEstudiante.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAddEstudianteActionPerformed(evt);
            }
        });

        jBtnChangeEstudiante.setBackground(new java.awt.Color(46, 204, 113));
        jBtnChangeEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        jBtnChangeEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/icons8_Change_User_16px_1.png"))); // NOI18N
        jBtnChangeEstudiante.setToolTipText("Cambiar Estudiante");
        jBtnChangeEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnChangeEstudiante.setIconTextGap(0);
        jBtnChangeEstudiante.setPreferredSize(new java.awt.Dimension(73, 20));
        jBtnChangeEstudiante.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnChangeEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAddEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnChangeEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBtnAddEstudiante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnChangeEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelExtra.setBackground(new java.awt.Color(250, 250, 250));

        jLabel11.setText("Fecha de Inicio:");

        jLabel12.setText("Fecha de Finalización:");

        jLabel13.setText("Total de Horas:");

        jLabel15.setText("Encargado:");

        jBtnLimpiar.setBackground(new java.awt.Color(127, 140, 141));
        jBtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/icons8_Broom_16px.png"))); // NOI18N
        jBtnLimpiar.setText("Limpiar");
        jBtnLimpiar.setIconTextGap(5);
        jBtnLimpiar.setPreferredSize(new java.awt.Dimension(73, 20));

        jBtnEditar.setBackground(new java.awt.Color(52, 152, 219));
        jBtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/icons8_Edit_16px.png"))); // NOI18N
        jBtnEditar.setText("Editar");
        jBtnEditar.setPreferredSize(new java.awt.Dimension(73, 20));

        jBtnRegistrar.setBackground(new java.awt.Color(46, 204, 113));
        jBtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/icons8_Add_File_16px.png"))); // NOI18N
        jBtnRegistrar.setText("Registrar");
        jBtnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnRegistrar.setPreferredSize(new java.awt.Dimension(73, 20));
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnRegistrarActionPerformed(evt);
            }
        });

        jSHoras.setModel(new javax.swing.SpinnerNumberModel(300, 25, 1000, 1));

        javax.swing.GroupLayout jPanelExtraLayout = new javax.swing.GroupLayout(jPanelExtra);
        jPanelExtra.setLayout(jPanelExtraLayout);
        jPanelExtraLayout.setHorizontalGroup(
            jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExtraLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTxtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTxtFin, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExtraLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelExtraLayout.createSequentialGroup()
                        .addComponent(jSHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jPanelExtraLayout.setVerticalGroup(
            jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExtraLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelExtraLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(26, 26, 26))
                    .addGroup(jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelExtraLayout.createSequentialGroup()
                        .addGroup(jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelExtraLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelExtraLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnEditar, jBtnLimpiar, jBtnRegistrar});

        jPanelTabla.setBackground(new java.awt.Color(250, 250, 250));

        jTablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablaSolicitudes.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTablaSolicitudesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaSolicitudes);

        jLabel7.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        jLabel7.setText("Seleccione la solicitud correspondiente:");

        javax.swing.GroupLayout jPanelTablaLayout = new javax.swing.GroupLayout(jPanelTabla);
        jPanelTabla.setLayout(jPanelTablaLayout);
        jPanelTablaLayout.setHorizontalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTablaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelTablaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(22, 22, 22))))
        );
        jPanelTablaLayout.setVerticalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTablaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanelInstitucion.setBackground(new java.awt.Color(250, 250, 250));

        jLabel5.setFont(new java.awt.Font("Product Sans", 0, 16)); // NOI18N
        jLabel5.setText("Institución");

        jLabel8.setText("Nombre de la Institución:");

        jTxtNombreInst.setEnabled(false);

        jLabel9.setText("Correo:");

        jTxtCorreoInst.setEnabled(false);

        jTxtTelefonoInst.setEnabled(false);

        jLabel10.setText("Teléfono");

        jLabel14.setText("Tipo de Institución:");

        jTxtTipoInst.setEnabled(false);

        jTxtIdSolicitud.setEnabled(false);

        jTxtIdInst.setEnabled(false);

        javax.swing.GroupLayout jPanelInstitucionLayout = new javax.swing.GroupLayout(jPanelInstitucion);
        jPanelInstitucion.setLayout(jPanelInstitucionLayout);
        jPanelInstitucionLayout.setHorizontalGroup(
            jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(221, 221, 221)
                .addComponent(jTxtIdSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtIdInst, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTxtNombreInst, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTxtCorreoInst, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTxtTelefonoInst, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jTxtTipoInst, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanelInstitucionLayout.setVerticalGroup(
            jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInstitucionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTxtTipoInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTxtTelefonoInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTxtCorreoInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNombreInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanelHojas.setBackground(new java.awt.Color(250, 250, 250));

        jTableHojas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableHojas);

        jLabel16.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        jLabel16.setText("Hojas de Servicio del Estudiante:");

        javax.swing.GroupLayout jPanelHojasLayout = new javax.swing.GroupLayout(jPanelHojas);
        jPanelHojas.setLayout(jPanelHojasLayout);
        jPanelHojasLayout.setHorizontalGroup(
            jPanelHojasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHojasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelHojasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelHojasLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        jPanelHojasLayout.setVerticalGroup(
            jPanelHojasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHojasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelInstitucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelExtra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelHojas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHojas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddEstudianteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnAddEstudianteActionPerformed
    {//GEN-HEADEREND:event_jBtnAddEstudianteActionPerformed
        llenarDatosEstudiante();
        jPanelHojas.setVisible(true);
    }//GEN-LAST:event_jBtnAddEstudianteActionPerformed

    private void jBtnChangeEstudianteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnChangeEstudianteActionPerformed
    {//GEN-HEADEREND:event_jBtnChangeEstudianteActionPerformed
        llenarDatosEstudiante();
        jPanelHojas.setVisible(true);
    }//GEN-LAST:event_jBtnChangeEstudianteActionPerformed

    private void jTablaSolicitudesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTablaSolicitudesMouseClicked
    {//GEN-HEADEREND:event_jTablaSolicitudesMouseClicked
        int fila = jTablaSolicitudes.getSelectedRow();
        int idSoli = Integer.parseInt(jTablaSolicitudes.getValueAt(fila, 0).toString());
        jTxtIdSolicitud.setText(String.valueOf(idSoli));
        llenarDatosInstituciones(idSoli);
        jPanelInstitucion.setVisible(true);
        jPanelExtra.setVisible(true);
        jBtnEditar.setEnabled(false);
    }//GEN-LAST:event_jTablaSolicitudesMouseClicked

    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnRegistrarActionPerformed
    {//GEN-HEADEREND:event_jBtnRegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    private void registrar()
    {
        try
        {
            HojaServicioSocial h = new HojaServicioSocial();
            h.setIdEstudiante(Integer.parseInt(this.jTxtIdEst.getText()));
            h.setIdInstitucion(Integer.parseInt(this.jTxtIdInst.getText()));
            h.setIdCoordinador(DaoCoordinador.idCoord);
            
            h.setEncargado(this.jTxtEncargado.getText());
            h.setFechaInicio(this.jTxtInicio.getText());
            h.setFechaFinalizacion(this.jTxtFin.getText());
            h.setHoras((int) this.jSHoras.getValue());
            
            daoH.insertarHoja(h);
             Console.tabla(daoH.mostrar(e.getId()), jTableHojas);

            
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    
    private void llenarDatosInstituciones(int idSoli)
    {
        i = daoS.getInstitucionSoli(idSoli);
        
        jTxtIdInst.setText(String.valueOf(i.getIdIns()));
        jTxtNombreInst.setText(i.getNombreIns());
        jTxtCorreoInst.setText(i.getCorreoIns());
        jTxtTelefonoInst.setText(i.getTeleIns());
        jTxtTipoInst.setText(daoI.getTipo(i.getIdTipo()).getDescripcion());
    }
    
    private void llenarDatosEstudiante()
    {
        Object[] cosa = new Object[2];

        try
        {
            String carnet = JOptionPane.showInputDialog("Ingrese el N° de Carnet del Estudiante").trim();

            cosa = daoS.solicitudesEstudiante(carnet);

            //JOptionPane.showMessageDialog(null, cosa[0]);
            if (cosa[0].equals("Datos"))
            {

                List lista = (List) cosa[1];
                
                llenarTablaSolicitudes(lista);
                
                s = (Solicitud) lista.get(0);
                
                int idEstudiante = s.getIdEstudiante();
                
                e = daoE.getEstudianteId(idEstudiante);

                jTxtIdEst.setText(String.valueOf(e.getId()));
                jTxtNombre.setText(e.getNombres());
                jTxtApellidos.setText(e.getApellidos());
                jTxtCarnet.setText(e.getCarnet());
                jTxtGrupo.setText(daoE.getGrupo(e.getIdGrupo()).getNombreGrupo());
                jPanelEstudiante.setVisible(true);
                jBtnAddEstudiante.setVisible(false);
                jBtnChangeEstudiante.setVisible(true);
                jPanelTabla.setVisible(true);
                
                jTableHojas.setVisible(true);
                Console.tabla(daoH.mostrar(e.getId()), jTableHojas);
            } else
            {
                JOptionPane.showMessageDialog(this, "No se encontró registro para este estudiante", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e)
        {
            //JOptionPane.showMessageDialog(null, "tugfa");
        }
    }

    private void llenarTablaSolicitudes(List lista)    
    {
        String[] columnas = {"N°", "Institución",  "Coordinador", "Fecha"};
        Object[] obj = new Object[4];
        DefaultTableModel tabla = new DefaultTableModel(null, columnas);
        
        try
        {
            for (int j = 0; j < lista.size(); j++)
            {
                Solicitud ss = new Solicitud();
                ss = (Solicitud) lista.get(j);
                
                obj[0] = ss.getId();
                obj[1] = daoI.nombreInstitucion(ss.getIdInstitucion());
                obj[2] = daoC.getCoordinador(ss.getIdCoordinador()).getNombres() + " " + daoC.getCoordinador(ss.getIdCoordinador()).getApellidos();
                obj[3] = ss.getFecha();
                
                tabla.addRow(obj);
            } 
            
            jTablaSolicitudes.setModel(tabla);
        } catch (Exception e)
        {
        }
    }

    private void limpiar()
    {
        
    }
    
    private void initUi()
    {
        jPanelTabla.setVisible(false);
        jPanelEstudiante.setVisible(false);
        ui.flatButton(jBtnAddEstudiante, "#2ECC71", "#28B463", "#58D68D");
        ui.flatButton(jBtnChangeEstudiante, "#3498DB", "#2E86C1", "#5DADE2");
        jBtnChangeEstudiante.setVisible(false);
        jTxtIdEst.setVisible(false);
        jTxtIdInst.setVisible(false);
        jTxtIdSolicitud.setVisible(false);
        jPanelInstitucion.setVisible(false);
        jPanelExtra.setVisible(false);
        jPanelHojas.setVisible(false);
        ui.flatButton(jBtnRegistrar, "#2ECC71", "#28B463", "#58D68D");
        ui.flatButton(jBtnEditar, "#3498DB", "#2E86C1", "#5DADE2");
        ui.flatButton(jBtnLimpiar, "#7F8C8D", "#707B7C", "#99A3A4");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jBtnAddEstudiante;
    private javax.swing.JButton jBtnChangeEstudiante;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JButton jBtnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelEstudiante;
    private javax.swing.JPanel jPanelExtra;
    private javax.swing.JPanel jPanelHojas;
    private javax.swing.JPanel jPanelInstitucion;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JSpinner jSHoras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaSolicitudes;
    private javax.swing.JTable jTableHojas;
    private javax.swing.JTextField jTxtApellidos;
    private javax.swing.JTextField jTxtCarnet;
    private javax.swing.JTextField jTxtCorreoInst;
    private javax.swing.JTextField jTxtEncargado;
    private javax.swing.JFormattedTextField jTxtFin;
    private javax.swing.JTextField jTxtGrupo;
    private javax.swing.JTextField jTxtIdEst;
    private javax.swing.JTextField jTxtIdInst;
    private javax.swing.JTextField jTxtIdSolicitud;
    private javax.swing.JFormattedTextField jTxtInicio;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtNombreInst;
    private javax.swing.JTextField jTxtTelefonoInst;
    private javax.swing.JTextField jTxtTipoInst;
    // End of variables declaration//GEN-END:variables
}
